apiVersion: apps/v1
kind: Deployment
metadata:
  name: BotApp
spec:
  selector:
    matchLabels:
      app: BotApp
  replicas: 1
  template:
    metadata:
      labels:
        app: BotApp
    spec:
      containers:
        - name: BotApp
          image: 700935310038.dkr.ecr.eu-west-2.amazonaws.com
          env:
            - name: ENV
              value: """
