apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: 700935310038.dkr.ecr.eu-west-2.amazonaws.com/idotbot:latest
        env:
          - name: ENV
            value: "dev"
